import type { Lesson, Section } from "@/lib/content";

type Spec = {
  slug: string; title: string; subtitle: string; minutes: number; tags: string[];
  problem: string; intuition: string; math: string; diagram: string; diagramLabel: string;
  scratch: string; compare: string; experiment: string; gotcha: string;
  question: string; options: string[]; correct: number; explanation: string; next: string;
};

const specs: Spec[] = [
  {
    slug: "numpy-ml-foundations", title: "NumPy Foundations for Machine Learning", subtitle: "The array operations beneath nearly every ML library.", minutes: 22, tags: ["NumPy", "Vectors", "Matrices", "Vectorization"],
    problem: "Machine-learning code repeatedly applies the same arithmetic to thousands of examples and features. Python loops make this slow and obscure the underlying mathematics.",
    intuition: "Store examples as rows of a matrix X and features as columns. A model keeps parameters in a vector w. One matrix-vector multiplication scores every example at once.",
    math: "For n examples with d features, X has shape (n, d), w has shape (d,), and X @ w has shape (n,). Broadcasting applies compatible operations across an axis without a loop.",
    diagram: "flowchart LR\n  X[Feature matrix X\nrows = examples] --> M[Matrix multiply X @ w]\n  W[Parameter vector w\none weight per feature] --> M\n  M --> P[Predictions for every row]",
    diagramLabel: "Vectorization turns one model expression into predictions for a whole batch.",
    scratch: "import numpy as np\n\nX = np.array([[2.0, 1.0], [0.0, 3.0], [1.0, 2.0]])\nw = np.array([4.0, -1.0])\nb = 0.5\npredictions = X @ w + b\nprint(predictions)  # [7.5, -2.5, 2.5]",
    compare: "# The equivalent loop is correct but less clear and slower\npredictions_loop = np.array([row @ w + b for row in X])\nassert np.allclose(predictions, predictions_loop)",
    experiment: "Check shapes after every operation with `print(X.shape)`. Intentionally transpose a vector and observe the error; shape literacy prevents a remarkable number of ML bugs.",
    gotcha: "Do not mix `(n,)`, `(n, 1)`, and `(1, n)` casually. NumPy broadcasting can silently produce an (n, n) array when you expected a vector. Assert shapes in early implementations.",
    question: "If X has shape (100, 5), what shape must w have for X @ w to produce 100 predictions?", options: ["(5,)", "(100,)", "(100, 5)", "(1, 100)"], correct: 0,
    explanation: "The inner dimensions must match: (100, 5) @ (5,) leaves one score for each of the 100 rows.", next: "Now use these operations to fit the simplest learnable model: linear regression.",
  },
  {
    slug: "linear-regression-gradient-descent", title: "Linear Regression with Gradient Descent", subtitle: "Fit a line by repeatedly following the direction that reduces error.", minutes: 30, tags: ["Linear regression", "Gradient descent", "MSE", "NumPy"],
    problem: "Given features such as size and location, predict a continuous target such as price. We want weights that generalize, not a hand-picked line.",
    intuition: "Make predictions, measure how wrong they are, then nudge each weight in the direction that lowers the error. Repeat until improvement slows.",
    math: "y-hat = Xw + b. With MSE = mean((y-hat - y)^2), gradients are dL/dw = (2/n) X-transpose (y-hat-y) and dL/db = 2 mean(y-hat-y). Update w = w - learning_rate times dL/dw.",
    diagram: "flowchart LR\n  A[Initialize weights] --> B[Predict: X @ w + b]\n  B --> C[Measure MSE loss]\n  C --> D[Compute gradients]\n  D --> E[Update weights]\n  E --> B\n  C --> F{Loss stable?}\n  F -- yes --> G[Trained model]",
    diagramLabel: "Gradient descent is a feedback loop: prediction, error, gradient, update.",
    scratch: "import numpy as np\n\ndef fit_linear(X, y, lr=0.05, epochs=1000):\n    w, b = np.zeros(X.shape[1]), 0.0\n    for _ in range(epochs):\n        error = X @ w + b - y\n        w -= lr * (2 / len(X)) * (X.T @ error)\n        b -= lr * 2 * error.mean()\n    return w, b\n\nw, b = fit_linear(X_train, y_train)",
    compare: "from sklearn.linear_model import LinearRegression\n\nreference = LinearRegression().fit(X_train, y_train)\nprint(reference.coef_, reference.intercept_)\n# With enough epochs and scaled features, your values should be close.",
    experiment: "Plot loss every 20 epochs. Try a learning rate 100 times too large and 100 times too small. One diverges; the other barely moves.",
    gotcha: "Gradient descent is sensitive to feature scale. If one feature is in rupees and another is a 0–1 flag, standardize inputs before using a shared learning rate.",
    question: "What does a gradient point toward?", options: ["The steepest increase in loss, so subtracting it reduces loss.", "The exact best weights in one step.", "The test set score.", "The nearest training example."], correct: 0,
    explanation: "The gradient is the local direction of fastest increase. Gradient descent moves in its negative direction.", next: "Regression gives numbers; next we adapt the same optimization loop to produce probabilities and classes.",
  },
  {
    slug: "logistic-regression-from-scratch", title: "Logistic Regression from Scratch", subtitle: "Learn binary classification through probabilities and cross-entropy.", minutes: 30, tags: ["Logistic regression", "Sigmoid", "Binary cross-entropy", "Classification"],
    problem: "A churn, fraud, or spam label is discrete. A plain linear score is unbounded, so it cannot be read directly as a probability.",
    intuition: "Keep the linear score, but pass it through an S-shaped sigmoid. Large positive scores approach one, large negative scores approach zero, and the model can express uncertainty in between.",
    math: "p = sigmoid(Xw+b) = 1/(1+exp(-z)). Binary cross-entropy is -mean(y log p + (1-y) log(1-p)). Its convenient gradient is X-transpose(p-y)/n.",
    diagram: "flowchart LR\n  X[Features] --> Z[Linear score z = X @ w + b]\n  Z --> S[Sigmoid]\n  S --> P[Probability of class 1]\n  P --> T{Threshold}\n  T --> L[Predicted label]",
    diagramLabel: "Logistic regression separates a probability estimate from the threshold used for a decision.",
    scratch: "def sigmoid(z):\n    return 1 / (1 + np.exp(-np.clip(z, -500, 500)))\n\ndef fit_logistic(X, y, lr=0.1, epochs=1000):\n    w, b = np.zeros(X.shape[1]), 0.0\n    for _ in range(epochs):\n        p = sigmoid(X @ w + b)\n        w -= lr * (X.T @ (p - y)) / len(X)\n        b -= lr * (p - y).mean()\n    return w, b",
    compare: "from sklearn.linear_model import LogisticRegression\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import make_pipeline\n\nreference = make_pipeline(StandardScaler(), LogisticRegression(max_iter=1000))\nreference.fit(X_train, y_train)",
    experiment: "After fitting, calculate probabilities and compare thresholds 0.3, 0.5, and 0.7 with a confusion matrix. The learned model stays fixed; only the business decision changes.",
    gotcha: "Clip probabilities before taking log in a hand-written loss function. `log(0)` creates infinity, which can make training diagnostics unusable.",
    question: "Why is binary cross-entropy preferred over MSE for logistic regression?", options: ["It strongly penalizes confident wrong probabilities and gives a well-behaved classification objective.", "It removes the sigmoid.", "It needs no labels.", "It makes all probabilities equal."], correct: 0,
    explanation: "Cross-entropy matches the Bernoulli probability model and responds sharply when the model is confidently wrong.", next: "The next unsupervised algorithm needs no target at all: K-Means discovers groups from distance.",
  },
  {
    slug: "kmeans-from-scratch", title: "K-Means Clustering from Scratch", subtitle: "Discover groups by alternating assignment and centroid updates.", minutes: 28, tags: ["K-Means", "Clustering", "Centroids", "Unsupervised learning"],
    problem: "Sometimes there is no answer column. You may want to explore customer segments or groups of similar products without pre-existing labels.",
    intuition: "Place K tentative centres, assign each point to the nearest centre, move every centre to its group's mean, and repeat. The groups settle when assignments stop changing.",
    math: "K-Means minimizes inertia: sum_i ||x_i - mu_(assigned_i)|| squared. Each centroid mu_k is the arithmetic mean of points assigned to cluster k.",
    diagram: "flowchart LR\n  A[Choose K centroids] --> B[Assign each point to nearest centroid]\n  B --> C[Move each centroid to its cluster mean]\n  C --> D{Assignments changed?}\n  D -- yes --> B\n  D -- no --> E[Clusters and centroids]",
    diagramLabel: "K-Means alternates an assignment step with a centroid-update step.",
    scratch: "def kmeans(X, k, steps=100, seed=42):\n    rng = np.random.default_rng(seed)\n    centers = X[rng.choice(len(X), size=k, replace=False)].astype(float)\n    for _ in range(steps):\n        labels = ((X[:, None] - centers[None, :]) ** 2).sum(axis=2).argmin(axis=1)\n        new_centers = np.array([X[labels == j].mean(axis=0) for j in range(k)])\n        if np.allclose(centers, new_centers): break\n        centers = new_centers\n    return labels, centers",
    compare: "from sklearn.cluster import KMeans\nfrom sklearn.preprocessing import StandardScaler\n\nX_scaled = StandardScaler().fit_transform(X)\nreference = KMeans(n_clusters=4, n_init=20, random_state=42).fit(X_scaled)\nprint(reference.inertia_)",
    experiment: "Run your implementation with different seeds. If clusters shift dramatically, use more restarts, inspect the data, and avoid overselling a fragile segmentation.",
    gotcha: "An empty cluster can occur when no points choose a centroid. A robust implementation must reinitialize that centroid rather than taking the mean of an empty slice.",
    question: "What does K-Means optimize?", options: ["The within-cluster sum of squared distances to centroids.", "Classification accuracy.", "The number of labelled examples.", "The largest possible distance between any two points."], correct: 0,
    explanation: "Its objective rewards compact clusters around their mean centres; it does not know whether a segment is business-useful.", next: "Trees make a different kind of prediction: a series of explicit, data-chosen rules.",
  },
  {
    slug: "decision-trees-from-scratch", title: "Decision Trees from Scratch", subtitle: "Choose splits that make child groups more pure.", minutes: 32, tags: ["Decision trees", "Gini impurity", "Recursion", "Splits"],
    problem: "Some patterns depend on conditional rules and interactions that a straight decision boundary cannot express clearly.",
    intuition: "A tree tries candidate questions such as 'tenure <= 6 months?' and keeps the one that produces cleaner child groups. It repeats the process recursively in each child.",
    math: "For class proportions p_k, Gini impurity = 1 - sum(p_k squared). A good split maximizes parent impurity minus the sample-weighted impurity of its children.",
    diagram: "flowchart TD\n  A[All training rows] --> B{Tenure <= 6?}\n  B -- yes --> C{Monthly charge > 80?}\n  B -- no --> D[Mostly retained]\n  C -- yes --> E[High churn risk]\n  C -- no --> F[Mixed group]",
    diagramLabel: "A tree represents a prediction as readable conditional decisions.",
    scratch: "def gini(y):\n    _, counts = np.unique(y, return_counts=True)\n    p = counts / len(y)\n    return 1 - np.sum(p ** 2)\n\ndef split_gain(y, left_mask):\n    left, right = y[left_mask], y[~left_mask]\n    if len(left) == 0 or len(right) == 0: return -np.inf\n    child = len(left)/len(y)*gini(left) + len(right)/len(y)*gini(right)\n    return gini(y) - child",
    compare: "from sklearn.tree import DecisionTreeClassifier\n\ntree = DecisionTreeClassifier(max_depth=4, min_samples_leaf=10, random_state=42)\ntree.fit(X_train, y_train)\nprint(tree.get_depth(), tree.get_n_leaves())",
    experiment: "For each numeric feature, test candidate thresholds and print the best gain. Then compare it with scikit-learn's first split to validate your reasoning.",
    gotcha: "A fully grown tree often memorizes training rows. Add stopping rules such as `max_depth` and `min_samples_leaf`, and choose them with validation data.",
    question: "Why are decision trees called greedy?", options: ["Each split chooses the best immediate impurity reduction, not the globally optimal full tree.", "They require every feature.", "They always overfit.", "They can only make two leaves."], correct: 0,
    explanation: "Searching every possible complete tree is infeasible. CART makes the locally best split at each node.", next: "Now build the common infrastructure that lets all these estimators share a familiar fit/predict API.",
  },
  {
    slug: "building-an-estimator-api", title: "Build a Tiny scikit-learn-Style API", subtitle: "Package algorithms as reusable, testable estimators.", minutes: 22, tags: ["API design", "fit", "predict", "Testing"],
    problem: "Notebook functions are difficult to compare, compose, serialize, and test. A consistent estimator interface makes an algorithm useful beyond one experiment.",
    intuition: "`fit` learns and stores parameters ending in an underscore. `predict` uses only those learned parameters. This separation prevents accidental retraining during inference.",
    math: "The contract is conceptual rather than new mathematics: fit maps (X, y) to learned parameters theta; predict maps (X, theta) to y-hat. The same theta must be used for every inference row.",
    diagram: "flowchart LR\n  A[Training X, y] --> B[fit]\n  B --> C[Learned parameters\nw_, b_, centroids_]\n  D[New X] --> E[predict]\n  C --> E\n  E --> F[Predictions]",
    diagramLabel: "Training and inference are separate stages joined by learned parameters.",
    scratch: "class LinearRegressionScratch:\n    def __init__(self, lr=0.05, epochs=1000):\n        self.lr, self.epochs = lr, epochs\n\n    def fit(self, X, y):\n        self.coef_ = np.zeros(X.shape[1]); self.intercept_ = 0.0\n        for _ in range(self.epochs):\n            err = X @ self.coef_ + self.intercept_ - y\n            self.coef_ -= self.lr * 2 * X.T @ err / len(X)\n            self.intercept_ -= self.lr * 2 * err.mean()\n        return self\n\n    def predict(self, X):\n        return X @ self.coef_ + self.intercept_",
    compare: "from sklearn.base import BaseEstimator, RegressorMixin\n\n# In a production library, inherit BaseEstimator so parameters work with\n# get_params, clone, Pipeline, and GridSearchCV.",
    experiment: "Write three tiny tests: predictions have the right shape, loss falls on a synthetic linear dataset, and calling `predict` before `fit` raises a helpful error.",
    gotcha: "Never learn normalization statistics inside `predict`. That changes the model depending on the batch it receives and creates training-serving skew.",
    question: "Why does `fit` conventionally return self?", options: ["It permits concise chaining such as model.fit(X, y).predict(X_new).", "It automatically cross-validates.", "It makes training parallel.", "It removes stored parameters."], correct: 0,
    explanation: "Returning the fitted estimator supports a composable, familiar API while learned attributes remain attached to the object.", next: "With estimators in place, learn the diagnostics that make optimization failures understandable.",
  },
  {
    slug: "optimization-debugging", title: "Debugging Optimization and Numerical Stability", subtitle: "Recognize divergence, slow learning, bad scales, and silent NaNs.", minutes: 26, tags: ["Debugging", "Optimization", "Numerical stability", "Learning curves"],
    problem: "From-scratch models fail in ways libraries often hide: loss explodes, training stalls, gradients become NaN, or outputs have surprising shapes.",
    intuition: "A learning curve is a vital sign. Healthy loss decreases smoothly before flattening. Divergence, oscillation, and a flat line each point to different causes.",
    math: "Finite-difference gradient checking approximates a derivative: dL/dw_j approximately equals [L(w_j+epsilon)-L(w_j-epsilon)]/(2 epsilon). Compare it to your analytic gradient on a small dataset.",
    diagram: "flowchart TD\n  A[Loss looks wrong] --> B{NaN or infinity?}\n  B -- yes --> C[Check logs, overflow, divide by zero]\n  B -- no --> D{Loss rises or oscillates?}\n  D -- yes --> E[Lower learning rate; scale features]\n  D -- no --> F{Loss flat?}\n  F -- yes --> G[Raise learning rate; check gradients and data]\n  F -- no --> H[Inspect validation gap]",
    diagramLabel: "A small diagnostic tree turns a vague training failure into targeted checks.",
    scratch: "def numerical_grad(loss_fn, w, j, eps=1e-5):\n    plus, minus = w.copy(), w.copy()\n    plus[j] += eps; minus[j] -= eps\n    return (loss_fn(plus) - loss_fn(minus)) / (2 * eps)\n\n# Compare numerical_grad(...) with your analytic gradient on one coefficient.",
    compare: "# Useful assertions during development\nassert np.isfinite(loss)\nassert predictions.shape == y.shape\nassert np.isfinite(grad_w).all()\n# Log loss, gradient norm, and validation score at regular intervals.",
    experiment: "Use a synthetic dataset with known coefficients. Your fitted weights should approach the known answer; if they do not, debug here before blaming real-world data.",
    gotcha: "Do not hide NaNs with `np.nan_to_num` as a first response. Locate their source: invalid input, a zero denominator, exponential overflow, or an unstable loss calculation.",
    question: "What is gradient checking best used for?", options: ["Verifying an analytic gradient on a small test case.", "Replacing gradients for full training.", "Choosing a train/test split.", "Clustering unlabelled data."], correct: 0,
    explanation: "Finite differences are slow and numerically approximate, but invaluable for confirming that a hand-derived gradient is correct.", next: "Put everything together in a small, NumPy-only model library and compare it honestly with scikit-learn.",
  },
  {
    slug: "numpy-ml-library-capstone", title: "Capstone: A NumPy-Only ML Mini Library", subtitle: "Turn the algorithms into a tested package and compare every result.", minutes: 34, tags: ["Capstone", "NumPy", "Testing", "Benchmarking"],
    problem: "Understanding arrives when you can implement, validate, and explain an algorithm—not merely call it. This capstone consolidates the track into a small reusable library.",
    intuition: "Build the same interface for linear regression, logistic regression, K-Means, and a shallow decision tree. Test on controlled data, then compare predictions and metrics to a trusted implementation.",
    math: "A valid comparison uses the same split, preprocessing, objective, and metric. Small numerical differences are normal; systematic disagreement points to an implementation, initialization, or convergence issue.",
    diagram: "flowchart LR\n  A[Implement estimator] --> B[Unit tests on synthetic data]\n  B --> C[Compare with scikit-learn]\n  C --> D{Results agree?}\n  D -- no --> E[Inspect shapes, loss, gradients, seeds]\n  E --> A\n  D -- yes --> F[Document limits and package API]",
    diagramLabel: "The capstone loop validates implementations before they are trusted.",
    scratch: "# Suggested package layout\n# scratchml/\n#   linear_model.py     # LinearRegressionScratch, LogisticRegressionScratch\n#   cluster.py          # KMeansScratch\n#   tree.py             # DecisionTreeScratch\n# tests/\n#   test_linear_model.py\n#   test_cluster.py\n\n# Each estimator exposes fit(X, y=None), predict(X), and learned *_ attributes.",
    compare: "# Compare held-out predictions, not only coefficients\nours = LinearRegressionScratch().fit(X_train, y_train).predict(X_test)\nreference = LinearRegression().fit(X_train, y_train).predict(X_test)\nprint(np.mean(np.abs(ours - reference)))\n# Also compare MAE against y_test.",
    experiment: "Write a README table with algorithm, objective, supported task, complexity, known limitations, and the closest scikit-learn class. This turns code into a portfolio-ready explanation.",
    gotcha: "Do not claim exact parity with scikit-learn. Mature libraries handle sparse inputs, edge cases, optimized solvers, input validation, and many years of numerical hardening.",
    question: "What is the strongest evidence that a scratch implementation is trustworthy?", options: ["It passes targeted tests and agrees with a reference on controlled and held-out data.", "Its code is short.", "It reaches zero training loss once.", "It has the same class name as scikit-learn."], correct: 0,
    explanation: "Tests establish local behavior; comparison with a trusted reference exposes errors that a single metric or dataset might hide.", next: "You now understand how core ML algorithms learn. Continue to Deep Learning to extend gradient-based learning to neural networks.",
  },
];

function lessonSections(s: Spec): Section[] {
  return [
    { step: 1, title: "The problem", blocks: [{ type: "text", content: s.problem }] },
    { step: 2, title: "Intuition", blocks: [{ type: "text", content: s.intuition }, { type: "callout", kind: "insight", content: "Implementing an algorithm exposes every assumption: data shape, objective, update rule, stopping condition, and numerical edge case." }] },
    { step: 3, title: "Visual explanation", blocks: [{ type: "diagram", chart: s.diagram, label: s.diagramLabel }] },
    { step: 4, title: "Mathematics", blocks: [{ type: "callout", kind: "math", content: s.math }] },
    { step: 5, title: "Build it from scratch", blocks: [{ type: "code", language: "python", label: "NumPy implementation", code: s.scratch }] },
    { step: 6, title: "Compare with a reference", blocks: [{ type: "code", language: "python", label: "scikit-learn comparison", code: s.compare }] },
    { step: 7, title: "Experiment", blocks: [{ type: "text", content: s.experiment }] },
    { step: 8, title: "Debugging checklist", blocks: [{ type: "list", style: "bullet", items: ["Verify input and output shapes.", "Use a tiny synthetic dataset with a known answer.", "Log loss or an appropriate objective over time.", "Set a seed whenever initialization is random.", "Compare to a trusted library on the same data."] }] },
    { step: 9, title: "Common mistake", blocks: [{ type: "callout", kind: "gotcha", content: s.gotcha }] },
    { step: 10, title: "Test yourself", blocks: [{ type: "quiz", question: s.question, options: s.options, correct: s.correct, explanation: s.explanation }] },
    { step: 11, title: "What is next", blocks: [{ type: "text", content: s.next }] },
  ];
}

export const mlFromScratchLessons: Lesson[] = specs.map((s, index) => ({
  slug: s.slug, trackSlug: "ml-from-scratch", order: index + 1, minutes: s.minutes,
  title: s.title, subtitle: s.subtitle, tags: s.tags, sections: lessonSections(s),
}));
