export type Level = "Foundations" | "AI Core" | "AI Engineering" | "Advanced";

export interface Track {
  slug: string;
  number: string;
  title: string;
  tagline: string;
  level: Level;
  hours: number;
  emoji: string;
  overview: string;
  topics: string[];
  projects: string[];
  outcomes: string[];
}

// Short, learner-friendly definitions shown beside concepts in all tracks.
// Keeping this separate from the curriculum list preserves the concise labels used
// in cards, while giving learners immediate context on the track page.
export const aiCoreTopicDescriptions: Record<string, Record<string, string>> = {
  "developer-setup": {
    Python: "The dominant language for AI — widely used, great libraries, readable syntax.",
    "Python virtual environments": "Isolated Python installations so project dependencies don't conflict.",
    pip: "Python's package installer — the standard way to install libraries from PyPI.",
    uv: "A fast, modern Python package manager and project tool — replaces pip, venv, and more.",
    Jupyter: "Interactive notebooks for exploratory data work, visualization, and sharing results.",
    "VS Code": "The code editor most AI engineers use — lightweight, extensible, great Python support.",
    Git: "Version control for code — track changes, collaborate, and never lose work.",
    GitHub: "Host your Git repos, collaborate with others, and showcase your portfolio.",
    "Linux basics": "Essential commands for navigating directories, editing files, and running scripts.",
    CLI: "Command-line interface — the terminal is faster and more powerful than GUI tools.",
    Docker: "Package your app and its dependencies into a container that runs anywhere.",
    "REST APIs": "The standard way web services communicate — HTTP requests and JSON responses.",
    JSON: "JavaScript Object Notation — the data format APIs use to exchange information.",
    HTTP: "The protocol that powers the web — GET, POST, status codes, headers.",
    "Environment variables": "Configuration values stored outside your code — API keys, secrets, settings.",
    "API keys": "Secret tokens that authenticate your requests to external APIs.",
    "GPU basics": "Graphics cards repurposed for AI — massively parallel computation for neural networks.",
    "CUDA basics": "NVIDIA's platform for running code on GPUs — required for PyTorch GPU training.",
    "Local AI setup": "Run models on your own machine instead of calling cloud APIs.",
    Ollama: "The easiest way to run LLMs locally — Llama, Mistral, Gemma, and more.",
  },
  "math-for-ai": {
    "Scalars, vectors, matrices, tensors": "Numbers (scalars), lists (vectors), tables (matrices), and higher-dimensional arrays (tensors).",
    "Dot product": "Multiply corresponding elements and sum — measures similarity or projects one vector onto another.",
    "Matrix multiplication": "Combine matrices by taking dot products of rows and columns — the core operation in neural networks.",
    "Norms & distance": "Measure the size of a vector (norm) or how far apart two vectors are (distance).",
    "Eigenvalues & eigenvectors": "Special vectors that only scale when a matrix multiplies them — reveal a matrix's fundamental directions.",
    PCA: "Principal Component Analysis — compress high-dimensional data into fewer dimensions that capture most variance.",
    Embeddings: "Represent discrete objects (words, images) as continuous vectors that capture semantic relationships.",
    Derivatives: "Measure how fast a function changes — the foundation of optimization.",
    "Partial derivatives": "Derivatives with respect to one variable while holding others constant.",
    "Chain rule": "Compute derivatives of composed functions — enables backpropagation through deep networks.",
    "Gradient descent": "Follow the negative gradient to iteratively find the minimum of a function.",
    "Probability & Bayes": "Quantify uncertainty and update beliefs given evidence using Bayes' theorem.",
    Distributions: "Patterns that describe how values are spread — normal, uniform, Bernoulli, and more.",
    "Expectation & variance": "The mean (expected value) and spread (variance) of a random variable.",
    "Maximum likelihood": "Find parameters that make the observed data most probable under your model.",
    "Sampling & hypothesis testing": "Draw samples to estimate distributions and test statistical claims.",
  },
  "classical-ml": {
    "Linear & polynomial regression": "Predict a number with a straight line, or a curved extension of one.",
    "Logistic regression": "Estimate the probability of a yes/no outcome, such as churn.",
    "Decision trees": "Learn if/then questions that split data into increasingly pure groups.",
    "Random forest": "Average many randomized decision trees for a more stable prediction.",
    "Gradient boosting": "Build small trees sequentially, with each one correcting earlier errors.",
    "XGBoost / LightGBM": "Fast, production-ready gradient-boosting libraries for tabular data.",
    "K-Means": "Group unlabeled points around K representative centres.",
    "Hierarchical clustering": "Build a tree of nested groups instead of choosing one fixed clustering first.",
    "DBSCAN": "Find dense groups and label isolated points as noise or anomalies.",
    "PCA & dimensionality reduction": "Compress many correlated features into fewer informative directions.",
    "Overfitting, underfitting, bias/variance": "Understand whether a model is too simple, too memorized, or balanced.",
    "Cross-validation": "Evaluate a model across several train/validation splits for a more reliable score.",
    "Feature engineering & selection": "Create useful inputs and retain the ones that add real predictive signal.",
    "Accuracy, precision, recall, F1, ROC-AUC": "Classification measures that expose different kinds of mistakes and ranking quality.",
    "MAE, MSE, RMSE, RÂ²": "Regression measures for average error, large errors, and explained variation.",
  },
  "ml-from-scratch": {
    "Linear regression from scratch": "Implement a numeric predictor and learn its weights without a library.",
    "Logistic regression from scratch": "Implement probability-based binary classification with sigmoid and gradients.",
    "K-means from scratch": "Code the assign-to-centroid and recompute-centroid clustering loop yourself.",
    "Decision tree fundamentals": "Calculate split quality and recursively form understandable rules.",
    "Gradient descent": "Repeatedly adjust parameters in the direction that reduces loss.",
    "Loss functions": "A numeric definition of how wrong a model's predictions are.",
    "Optimization": "The process used to minimize loss and find useful model parameters.",
    "Evaluation from scratch": "Compute metrics yourself to understand exactly what a score represents.",
  },
  "deep-learning": {
    "Neuron & perceptron": "A small unit that combines inputs and produces an activation.",
    "Weights & bias": "Learned numbers that control how strongly inputs affect a neuron.",
    "Sigmoid, tanh, ReLU, GELU, softmax": "Activation functions that add nonlinearity or turn scores into probabilities.",
    "Forward propagation": "Pass input through each layer to produce a prediction.",
    "Backpropagation": "Send error information backward to calculate how every weight should change.",
    "MSE, BCE, CCE loss": "Loss functions for numeric prediction, binary classes, and multiple classes.",
    "SGD, momentum, AdaGrad, RMSProp, Adam, AdamW": "Different rules for updating weights efficiently during training.",
    "Dropout & weight decay": "Regularization techniques that reduce memorization of training data.",
    "Batch & layer normalization": "Normalize intermediate activations to make training more stable.",
    "Early stopping": "Stop training when validation performance stops improving.",
  },
  pytorch: {
    "Installation": "Set up PyTorch with the CPU or GPU build that matches your machine.",
    "Tensors & operations": "PyTorch's multidimensional arrays and their fast mathematical operations.",
    Autograd: "Automatic differentiation that calculates gradients for tensor operations.",
    "Datasets & DataLoaders": "Organize examples and feed them to training in efficient batches.",
    "Models & modules": "Define reusable neural-network layers and complete model architectures.",
    "Training loops": "The repeatable sequence of forward pass, loss, backward pass, and update.",
    Evaluation: "Measure a trained model with gradients disabled on unseen data.",
    "GPU training": "Move tensors and models to accelerated hardware for faster computation.",
    "Saving & loading models": "Persist learned weights and restore them for inference or further training.",
    "Transfer learning": "Start from a pretrained model and adapt it to a smaller related task.",
  },
  "computer-vision": {
    "Image representation & RGB": "Represent pixels as numerical color channels a model can process.",
    "Convolution, kernels, stride, padding": "Slide learnable filters across images while controlling output size and detail.",
    Pooling: "Downsample feature maps while keeping their most useful local information.",
    CNNs: "Neural networks built from convolutions to learn visual patterns hierarchically.",
    "Transfer learning": "Fine-tune a vision model that already learned broad visual features.",
    "Object detection": "Locate and classify multiple objects with bounding boxes.",
    "Image segmentation": "Assign a class label to every pixel, not just the whole image.",
    OCR: "Convert text visible in an image or document into machine-readable characters.",
    "Vision Transformers": "Apply attention-based Transformer architectures to image patches.",
  },
  nlp: {
    "Text preprocessing": "Clean and normalize raw text before turning it into model inputs.",
    Tokenization: "Split text into the words, subwords, or symbols a model consumes.",
    "Stemming & lemmatization": "Reduce related word forms to a simpler shared root or dictionary form.",
    "N-grams & TF-IDF": "Represent text using word sequences and their importance across documents.",
    "Word embeddings (Word2Vec, GloVe)": "Dense vectors that place words with related meanings near each other.",
    "Semantic similarity": "Measure how alike two pieces of text are in meaning rather than exact wording.",
    "RNN, LSTM, GRU": "Sequence models that carry information from earlier tokens to later ones.",
    Attention: "Let a model selectively focus on the most relevant parts of an input.",
  },
  transformers: {
    Attention: "The mechanism that lets a model weigh which parts of the input matter most for each output.",
    "Query, Key, Value": "Three learned projections that determine what information flows through attention.",
    "Scaled dot-product attention": "Score query-key similarity, scale by dimension, and weight the values.",
    "Self-attention": "Attention where every position attends to every other position in the same sequence.",
    "Multi-head attention": "Run several attention operations in parallel to capture different relationships.",
    "Positional encoding": "Add position information to embeddings so the model knows word order.",
    "Feed-forward networks": "A two-layer MLP applied independently to each position after attention.",
    "Residual connections": "Skip connections that add the input back to the output, stabilizing deep networks.",
    "Layer normalization": "Normalize activations across features to speed up training and improve stability.",
    "Encoder & decoder": "Encoder processes input; decoder generates output, optionally attending to encoder states.",
    "Causal masking": "Prevent positions from attending to future positions, required for autoregressive generation.",
  },
  "generative-ai": {
    "Generative models": "Models that learn the distribution of data and can sample new examples from it.",
    Autoencoders: "Compress input to a latent code, then reconstruct — learns useful representations.",
    "Variational Autoencoders": "Autoencoders with a probabilistic latent space, enabling controlled generation.",
    GANs: "Two networks compete: a generator creates fakes, a discriminator learns to detect them.",
    Diffusion: "Learn to reverse a noise process — the current state-of-the-art for image generation.",
    "Text generation": "Sample tokens autoregressively from a language model's probability distribution.",
    "Image generation": "Synthesize images from noise, text prompts, or latent codes using VAEs, GANs, or diffusion.",
    "Multimodal generation": "Generate across modalities — text-to-image, image-to-text, or joint generation.",
  },
  "llm-from-scratch": {
    "Tokenizer & vocabulary": "Break text into subword units and map them to integers the model consumes.",
    "Token IDs": "Integer representations of tokens — the actual input to embedding layers.",
    Embeddings: "Learned dense vectors that represent each token in a continuous space.",
    "Positional encoding": "Add position information to embeddings so the model knows sequence order.",
    Attention: "Let each token attend to all previous tokens to gather context.",
    "Transformer block": "Self-attention, feedforward network, residuals, and normalization — the GPT building block.",
    "Language modeling": "Predict the next token given all previous tokens — the training objective for GPT.",
    "Training loop": "Forward pass, compute loss, backpropagate, update weights, repeat on billions of tokens.",
    "Inference & sampling": "Generate text by sampling the next token from the model's probability distribution.",
  },
  "llm-engineering": {
    "Zero-shot & few-shot": "Give the model a task with no examples, or 2-5 examples to teach the pattern.",
    "Role prompting": "Tell the model who it is and what constraints apply — sets context for the conversation.",
    "Structured prompts": "Use delimiters, XML tags, or templates to compose prompts programmatically.",
    "Output constraints": "Force specific formats, lengths, tones, or forbidden content through prompt instructions.",
    "Context windows & compression": "Every model has a token limit; manage it with truncation, summarization, or caching.",
    "Long-context strategies": "Handle documents longer than the context window via chunking, MapReduce, or retrieval.",
    "Structured output (JSON schema)": "Enforce valid JSON with defined fields and types, not free-form text.",
    "Function calling & tools": "Let the LLM decide when to call functions and what arguments to pass.",
  },
  "embeddings-vector-db": {
    Embeddings: "Dense numerical vectors that represent text, images, or other data in semantic space.",
    "Semantic similarity": "Measure how similar two pieces of content are by the distance between their embeddings.",
    "Cosine similarity": "Measure the angle between two vectors — the standard metric for embedding similarity.",
    "Vector search": "Find the nearest neighbors to a query vector among millions of stored vectors.",
    "Approximate nearest neighbor": "Trade perfect accuracy for speed using HNSW, IVF, or other indexing structures.",
    HNSW: "Hierarchical Navigable Small World graphs — the dominant ANN algorithm in vector databases.",
    "Chunking strategies": "Split documents into pieces that preserve meaning without exceeding embedding model limits.",
    "Metadata & filtering": "Store and filter on structured attributes alongside vectors — dates, tags, categories.",
    "Hybrid search": "Combine keyword search (BM25) with semantic search for better retrieval.",
    Reranking: "Re-score retrieved candidates with a more expensive model to improve ranking quality.",
  },
  rag: {
    "Document loading": "Ingest PDFs, Word docs, HTML, or databases into a format the pipeline can process.",
    Chunking: "Split documents into retrievable units — balance size, overlap, and semantic coherence.",
    Embedding: "Convert each chunk into a vector that captures its meaning.",
    "Vector DB": "Store millions of chunk embeddings and retrieve the most relevant for a given query.",
    Retriever: "The component that takes a query and returns the top-k most relevant chunks.",
    "Parent-child retrieval": "Retrieve small chunks for ranking, but return their full parent documents for context.",
    "Hybrid retrieval": "Combine dense vector search with sparse keyword search for better recall.",
    "Metadata filtering": "Pre-filter chunks by attributes like date, source, or author before semantic search.",
    "Query rewriting": "Rephrase the user's question into a better retrieval query using an LLM.",
    "Multi-query retrieval": "Generate several query variations and union their results for broader coverage.",
    HyDE: "Generate a hypothetical answer, embed it, and retrieve chunks similar to that answer.",
    Reranking: "Re-score retrieved chunks with a cross-encoder to improve precision.",
    "Context compression": "Extract only the sentences relevant to the query from each retrieved chunk.",
    "Graph RAG": "Build a knowledge graph from documents and traverse it during retrieval.",
    "Agentic RAG": "Let an agent decide when to retrieve, what to retrieve, and when to stop.",
    "Corrective RAG": "Let the model critique its retrieved context and retry retrieval if quality is low.",
    "Self-RAG": "The model decides whether to retrieve at all, and self-evaluates its own outputs.",
  },
  "fine-tuning": {
    Pretraining: "Train a model from scratch on massive unlabeled data to learn general representations.",
    "Transfer learning": "Start from a pretrained model and adapt it to a downstream task with less data.",
    "Fine-tuning": "Continue training a pretrained model on task-specific data to specialize it.",
    "Instruction tuning": "Fine-tune on instruction-response pairs to make the model follow instructions better.",
    SFT: "Supervised fine-tuning — train on labeled examples with standard cross-entropy loss.",
    LoRA: "Low-Rank Adaptation — freeze the base model, train small adapter matrices instead.",
    QLoRA: "Quantized LoRA — run LoRA on a quantized base model to fit on consumer GPUs.",
    PEFT: "Parameter-Efficient Fine-Tuning — update only a small fraction of parameters.",
    "Dataset preparation": "Collect, clean, format, and split examples into training and validation sets.",
    Evaluation: "Measure fine-tuned model quality on held-out data with task-specific metrics.",
    "Catastrophic forgetting": "When fine-tuning erases the model's original capabilities — mitigate with data mixing.",
  },
  "llm-evaluation": {
    "Accuracy, precision, recall, F1": "Traditional classification metrics — still useful for closed-ended LLM tasks.",
    Faithfulness: "Does the output accurately reflect the retrieved context without hallucination?",
    Relevance: "Is the output actually useful and on-topic for the user's query?",
    Groundedness: "Is every claim in the output supported by the provided context?",
    "Context precision & recall": "Were the right chunks retrieved, and were irrelevant chunks excluded?",
    "Hallucination detection": "Identify when the model makes up facts not present in the context.",
    "Toxicity & bias": "Measure harmful, offensive, or biased outputs using classifiers or LLM judges.",
    "LLM as judge": "Use a strong LLM to score outputs on quality dimensions — cheaper than human eval.",
  },
  "ai-agents": {
    "Tool calling": "The LLM decides which function to invoke and what arguments to pass.",
    "Agent loop": "Observe → Think → Act → Observe — the cycle that powers autonomous agents.",
    ReAct: "Reasoning + Acting — the agent explains its reasoning before each action.",
    Planning: "Break a complex task into subtasks, execute them, and adjust the plan as you go.",
    Memory: "Store conversation history, facts, or prior actions so the agent can reference them later.",
    Reflection: "Let the agent critique its own actions and outputs to improve over time.",
    "Self-correction": "When the agent detects an error, retry the action or revise the approach.",
    "Task decomposition": "Split a large goal into smaller, verifiable steps the agent can execute sequentially.",
    Routing: "Decide which specialist agent or tool should handle each subtask.",
    "Human-in-the-loop": "Pause for human approval before taking risky or irreversible actions.",
  },
  "langchain-langgraph": {
    "Prompt templates": "Parameterized strings for building prompts dynamically with variables.",
    "Models & tools": "Unified interfaces for calling LLMs and defining tools they can invoke.",
    Retrievers: "Abstractions for fetching relevant documents from vector stores or search APIs.",
    Chains: "Compose LLM calls, retrieval, and logic into reusable sequences.",
    "Structured output": "Parse LLM responses into typed objects using Pydantic schemas.",
    "LangGraph nodes & edges": "Build agent workflows as state machines with explicit control flow.",
    "State management": "Track agent state across steps — memory, intermediate results, branching logic.",
    "Retry logic": "Automatically retry failed LLM calls or tool invocations with backoff.",
    "Human approval nodes": "Pause execution and wait for a human to approve before continuing.",
  },
  mcp: {
    "What is MCP?": "Model Context Protocol — a standard for connecting AI assistants to tools and data sources.",
    "MCP Client & Server": "Clients request capabilities, servers provide tools, resources, and prompts.",
    Resources: "Data sources the server exposes — files, database rows, API responses.",
    Tools: "Functions the LLM can call to perform actions — search, create, update, delete.",
    Prompts: "Pre-written prompt templates the server offers for common tasks.",
    Transport: "How messages flow — stdio for local, SSE for remote connections.",
    Security: "Authentication, authorization, and sandboxing to prevent malicious tool use.",
    Authentication: "Verify the identity of clients connecting to MCP servers.",
  },
  "multi-agent": {
    "Supervisor & worker agents": "One agent coordinates, delegates tasks, and aggregates results from specialists.",
    Delegation: "The supervisor agent assigns subtasks to worker agents based on their expertise.",
    Communication: "Agents share messages, context, or results through a shared bus or direct channels.",
    "Shared memory": "A common knowledge base or context store all agents can read and write to.",
    "Agent routing": "Decide which agent should handle each incoming request or subtask.",
    "Consensus & debate": "Multiple agents propose solutions, critique each other, and converge on the best answer.",
    "Parallel agents": "Run several agents concurrently to speed up independent subtasks.",
    "Sequential agents": "Chain agents where each one's output becomes the next one's input.",
    "Hierarchical agents": "Organize agents in layers — executives, managers, workers — for complex workflows.",
  },
  multimodal: {
    "Vision + LLM": "Combine image understanding with language generation for tasks like captioning or VQA.",
    "Audio + LLM": "Integrate speech recognition or audio analysis with language models.",
    "Video + LLM": "Process video frames and temporal information alongside text generation.",
    "Image understanding": "Extract objects, text, scenes, or actions from images using vision models.",
    "Document understanding": "Parse structured documents like invoices, forms, or receipts with layout and OCR.",
    OCR: "Optical Character Recognition — extract text from images or scanned documents.",
    "Speech-to-text": "Convert spoken audio into text transcriptions using ASR models.",
    "Text-to-speech": "Synthesize natural-sounding speech from text using TTS models.",
  },
  "ai-and-databases": {
    "SQL fundamentals": "The query language for relational databases — SELECT, JOIN, WHERE, GROUP BY.",
    "Text-to-SQL": "Generate SQL queries from natural language questions using an LLM.",
    "Database agents": "Agents that understand schema, generate queries, execute them, and explain results.",
    "Schema understanding": "Retrieve table names, column types, relationships, and sample rows for context.",
    "Query generation": "Use the LLM to write SQL based on the schema and user question.",
    "Query validation": "Check generated SQL for syntax errors, security issues, or logical flaws before executing.",
    "Query execution": "Run the validated query against the database and return results.",
    "Result interpretation": "Summarize query results in natural language for the user.",
    "Row-level permissions": "Enforce access control so users only see data they're authorized to view.",
    Security: "Prevent SQL injection, validate queries, and sandbox execution to protect the database.",
  },
  "ai-infrastructure": {
    "FastAPI, vLLM, TGI, Ollama": "Frameworks for serving LLMs — from local dev (Ollama) to production scale (vLLM, TGI).",
    "Model serving & streaming": "Expose models via HTTP APIs with token-by-token streaming for low latency.",
    "Docker & Kubernetes": "Containerize models and orchestrate them at scale with auto-scaling and load balancing.",
    "GPU & CUDA": "Use accelerated hardware to run models fast — requires CUDA-compatible drivers and libraries.",
    "AWS / Azure / GCP": "Cloud platforms for deploying AI workloads — GPUs, serverless, managed inference.",
    Batching: "Group multiple requests together and process them in one forward pass to improve throughput.",
    "Caching & KV cache": "Cache attention key-value pairs across tokens to avoid recomputing them on every step.",
    Quantization: "Reduce model precision (FP32 → INT8 → INT4) to cut memory and speed up inference.",
    "Model & data parallelism": "Split the model across GPUs (model parallel) or batch across GPUs (data parallel).",
  },
  "ai-security": {
    "Prompt injection": "Malicious input that tricks the model into ignoring instructions or leaking data.",
    Jailbreaking: "Bypass safety filters by rephrasing harmful requests in creative ways.",
    "Data leakage": "Accidentally exposing training data, API keys, or user information through model outputs.",
    PII: "Personally Identifiable Information — must be filtered, masked, or never sent to the LLM.",
    "Model abuse": "Use the model for purposes it wasn't intended for — spam, phishing, misinformation.",
    "Tool abuse": "Trick the agent into calling dangerous tools or APIs with malicious arguments.",
    "Excessive agency": "The agent takes actions it shouldn't without proper authorization or human oversight.",
    "RAG poisoning": "Inject malicious content into the retrieval corpus to manipulate the model's responses.",
    "Supply-chain attacks": "Compromise dependencies, datasets, or pretrained weights to backdoor the system.",
    "Authentication & authorization": "Verify user identity and enforce access control on tools and data.",
    "Audit logging": "Record every LLM call, tool invocation, and data access for forensics and compliance.",
    Guardrails: "Pre-flight and post-flight filters that block harmful inputs or outputs before they reach users.",
  },
  "ai-production": {
    Architecture: "Design scalable, maintainable systems — API gateways, queues, workers, databases.",
    "API design": "RESTful or streaming endpoints that handle LLM calls, tool use, and session state.",
    "Async processing & queues": "Offload long-running tasks to background workers to keep APIs responsive.",
    Caching: "Store LLM responses, embeddings, or retrieval results to reduce cost and latency.",
    Observability: "Instrument your system so you can see what's happening in production.",
    "Logging & metrics": "Track request counts, latencies, error rates, token usage, and costs.",
    Tracing: "Follow a request through every service and LLM call to debug failures or slowness.",
    "Cost & token monitoring": "Measure and alert on token spend to avoid surprise bills.",
    "Rate limiting & retries": "Throttle requests to stay within API limits; retry transient failures with backoff.",
    "Circuit breakers": "Stop calling a failing service to prevent cascading failures.",
    "Model fallback": "Switch to a cheaper or faster model when the primary one is unavailable or too slow.",
    Versioning: "Track prompt, model, and pipeline versions so you can reproduce and roll back changes.",
    "CI/CD": "Automate testing and deployment so prompt changes don't break production.",
    Testing: "Unit tests for prompts, integration tests for pipelines, regression tests for quality.",
  },
  "ai-system-design": {
    "Requirements & constraints": "Define what the system must do, how fast, how cheap, and for how many users.",
    Architecture: "High-level design — API, backend, LLM, database, caching, queues, scaling strategy.",
    "Components & data flow": "Break the system into services and show how data and requests move through them.",
    "API design": "Define endpoints, request/response formats, authentication, and rate limits.",
    "Database choices": "Relational, vector, cache, graph — pick the right storage for each kind of data.",
    "LLM placement": "Decide where LLM calls happen — frontend, backend, edge, or a separate inference service.",
    Scaling: "How to handle 10x, 100x, or 1000x traffic — horizontal scaling, caching, batching, queuing.",
    Security: "Threat model the system, add guardrails, auth, audit logs, and data isolation.",
    Cost: "Estimate token spend, GPU costs, and infrastructure — design for the budget.",
    "Failure scenarios": "What happens when the LLM is down, slow, or wrong? How do you recover?",
  },
  capstone: {
    "Requirements & scoping": "Define what you're building, for whom, and what success looks like.",
    "Architecture design": "Plan the system — services, data flow, models, databases, and deployment.",
    "Iterative delivery": "Ship in phases — MVP first, then iterate based on feedback and metrics.",
    "Evaluation & testing": "Build automated tests for correctness, quality, and regressions.",
    Deployment: "Get the project live — cloud, on-prem, or local, with CI/CD and monitoring.",
    Documentation: "Write a README, architecture doc, and runbook so others can use and extend it.",
    "Demo & write-up": "Record a demo, write a case study, and publish it as a portfolio piece.",
  },
};

export function getTopicDescription(trackSlug: string, topic: string): string | undefined {
  return aiCoreTopicDescriptions[trackSlug]?.[topic];
}

export const tracks: Track[] = [
  {
    slug: "developer-setup",
    number: "00",
    title: "Developer Setup",
    tagline: "Build a local AI development environment from scratch.",
    level: "Foundations",
    hours: 6,
    emoji: "🧰",
    overview:
      "Every AI engineer needs a rock-solid local setup. In this track you install Python, learn virtual environments and package managers, get comfortable with Git, Docker, and the command line, and stand up your first local LLM through Ollama.",
    topics: [
      "Python",
      "Python virtual environments",
      "pip",
      "uv",
      "Jupyter",
      "VS Code",
      "Git",
      "GitHub",
      "Linux basics",
      "CLI",
      "Docker",
      "REST APIs",
      "JSON",
      "HTTP",
      "Environment variables",
      "API keys",
      "GPU basics",
      "CUDA basics",
      "Local AI setup",
      "Ollama",
    ],
    projects: ["Local AI Development Environment (React + FastAPI + Ollama)"],
    outcomes: [
      "Run a local LLM on your own machine",
      "Ship a React frontend that talks to a FastAPI backend",
      "Manage Python dependencies with uv confidently",
    ],
  },
  {
    slug: "math-for-ai",
    number: "01",
    title: "Mathematics for AI",
    tagline: "Just enough linear algebra, calculus, probability, and stats.",
    level: "Foundations",
    hours: 20,
    emoji: "📐",
    overview:
      "The math you actually need for AI — nothing more, nothing less. Vectors, gradients, probability, and statistics taught through code and visualization, not proofs.",
    topics: [
      "Scalars, vectors, matrices, tensors",
      "Dot product",
      "Matrix multiplication",
      "Norms & distance",
      "Eigenvalues & eigenvectors",
      "PCA",
      "Embeddings",
      "Derivatives",
      "Partial derivatives",
      "Chain rule",
      "Gradient descent",
      "Probability & Bayes",
      "Distributions",
      "Expectation & variance",
      "Maximum likelihood",
      "Sampling & hypothesis testing",
    ],
    projects: ["House Price Predictor built purely from gradients"],
    outcomes: [
      "Read AI papers without getting lost in notation",
      "Derive gradient updates by hand",
      "Understand why embeddings work geometrically",
    ],
  },
  {
    slug: "classical-ml",
    number: "02",
    title: "Classical Machine Learning",
    tagline: "The algorithms that still power 80% of ML in production.",
    level: "AI Core",
    hours: 24,
    emoji: "🌲",
    overview:
      "Regression, trees, gradient boosting, clustering, and evaluation. You will train, evaluate, and debug real models on real data.",
    topics: [
      "Linear & polynomial regression",
      "Logistic regression",
      "Decision trees",
      "Random forest",
      "Gradient boosting",
      "XGBoost / LightGBM",
      "K-Means",
      "Hierarchical clustering",
      "DBSCAN",
      "PCA & dimensionality reduction",
      "Overfitting, underfitting, bias/variance",
      "Cross-validation",
      "Feature engineering & selection",
      "Accuracy, precision, recall, F1, ROC-AUC",
      "MAE, MSE, RMSE, R²",
    ],
    projects: [
      "Customer Churn Predictor",
      "Loan Approval Predictor",
      "House Price Predictor",
      "Fraud Detection",
      "Customer Segmentation",
    ],
    outcomes: [
      "Pick the right algorithm for a tabular problem",
      "Diagnose overfitting from a learning curve",
      "Explain a model to a business stakeholder",
    ],
  },
  {
    slug: "ml-from-scratch",
    number: "03",
    title: "ML From Scratch",
    tagline: "Build the algorithms before you use the library.",
    level: "AI Core",
    hours: 18,
    emoji: "🧪",
    overview:
      "Implement linear regression, logistic regression, k-means, decision trees, and gradient descent using only Python and NumPy — then compare against scikit-learn line-for-line.",
    topics: [
      "Linear regression from scratch",
      "Logistic regression from scratch",
      "K-means from scratch",
      "Decision tree fundamentals",
      "Gradient descent",
      "Loss functions",
      "Optimization",
      "Evaluation from scratch",
    ],
    projects: ["Numpy-only ML library that mirrors scikit-learn's API"],
    outcomes: [
      "Never treat an ML algorithm as a black box again",
      "Reason about numerical stability",
      "Debug convergence issues from first principles",
    ],
  },
  {
    slug: "deep-learning",
    number: "04",
    title: "Deep Learning",
    tagline: "Neural networks, backprop, and the optimizers that make them learn.",
    level: "AI Core",
    hours: 28,
    emoji: "🧠",
    overview:
      "From a single neuron to deep networks. You will implement backpropagation by hand, then use it to train a network on real data.",
    topics: [
      "Neuron & perceptron",
      "Weights & bias",
      "Sigmoid, tanh, ReLU, GELU, softmax",
      "Forward propagation",
      "Backpropagation",
      "MSE, BCE, CCE loss",
      "SGD, momentum, AdaGrad, RMSProp, Adam, AdamW",
      "Dropout & weight decay",
      "Batch & layer normalization",
      "Early stopping",
    ],
    projects: ["Handwritten neural network trained on MNIST — no framework"],
    outcomes: [
      "Derive backpropagation from calculus",
      "Choose an optimizer with intent, not superstition",
      "Debug vanishing/exploding gradients",
    ],
  },
  {
    slug: "pytorch",
    number: "05",
    title: "PyTorch",
    tagline: "The framework used by every serious AI lab and startup.",
    level: "AI Core",
    hours: 16,
    emoji: "🔥",
    overview:
      "Tensors, autograd, datasets, dataloaders, training loops. You'll build a full training pipeline and train on GPU.",
    topics: [
      "Installation",
      "Tensors & operations",
      "Autograd",
      "Datasets & DataLoaders",
      "Models & modules",
      "Training loops",
      "Evaluation",
      "GPU training",
      "Saving & loading models",
      "Transfer learning",
    ],
    projects: ["MNIST classifier with an interactive hyperparameter panel"],
    outcomes: [
      "Write idiomatic PyTorch code",
      "Move workloads to GPU without breaking anything",
      "Save, load, and share trained models",
    ],
  },
  {
    slug: "computer-vision",
    number: "06",
    title: "Computer Vision",
    tagline: "Teach machines to see — from pixels to Vision Transformers.",
    level: "AI Core",
    hours: 20,
    emoji: "👁️",
    overview:
      "How images become tensors, how convolutions extract features, and how modern vision models detect, segment, and understand images.",
    topics: [
      "Image representation & RGB",
      "Convolution, kernels, stride, padding",
      "Pooling",
      "CNNs",
      "Transfer learning",
      "Object detection",
      "Image segmentation",
      "OCR",
      "Vision Transformers",
    ],
    projects: [
      "Face Detection",
      "Document Scanner",
      "Invoice OCR",
      "Plant Disease Detection",
      "Vehicle Detection",
      "Object Counter",
    ],
    outcomes: [
      "Fine-tune a pretrained CNN in an afternoon",
      "Build an OCR pipeline that reads real invoices",
      "Deploy a vision model behind an API",
    ],
  },
  {
    slug: "nlp",
    number: "07",
    title: "Natural Language Processing",
    tagline: "From bag-of-words to attention — the road that led to LLMs.",
    level: "AI Core",
    hours: 18,
    emoji: "💬",
    overview:
      "Understand the entire NLP evolution: tokenization, TF-IDF, word embeddings, RNNs, LSTMs, and finally attention. Every step in context.",
    topics: [
      "Text preprocessing",
      "Tokenization",
      "Stemming & lemmatization",
      "N-grams & TF-IDF",
      "Word embeddings (Word2Vec, GloVe)",
      "Semantic similarity",
      "RNN, LSTM, GRU",
      "Attention",
    ],
    projects: ["Text classifier", "Semantic similarity engine", "Simple translator"],
    outcomes: [
      "Explain why attention replaced recurrence",
      "Build a working sentence-similarity model",
      "Preprocess messy text like a pro",
    ],
  },
  {
    slug: "transformers",
    number: "08",
    title: "Transformers",
    tagline: "The single architecture behind every modern AI system.",
    level: "AI Engineering",
    hours: 20,
    emoji: "⚡",
    overview:
      "Query, key, value. Self-attention, multi-head attention, positional encoding, encoders, decoders. Interactive visualizations for every step.",
    topics: [
      "Attention",
      "Query, Key, Value",
      "Scaled dot-product attention",
      "Self-attention",
      "Multi-head attention",
      "Positional encoding",
      "Feed-forward networks",
      "Residual connections",
      "Layer normalization",
      "Encoder & decoder",
      "Causal masking",
    ],
    projects: ["Attention visualizer", "Toy encoder-decoder built in PyTorch"],
    outcomes: [
      "Draw the Transformer architecture from memory",
      "Explain why attention scales better than RNNs",
      "Read the original 'Attention is All You Need' paper with clarity",
    ],
  },
  {
    slug: "generative-ai",
    number: "09",
    title: "Generative AI",
    tagline: "Autoencoders, VAEs, GANs, and diffusion.",
    level: "AI Engineering",
    hours: 16,
    emoji: "🎨",
    overview:
      "How machines generate — text, images, audio. Autoencoders and VAEs for reconstruction, GANs for adversarial generation, diffusion for state-of-the-art image models.",
    topics: [
      "Generative models",
      "Autoencoders",
      "Variational Autoencoders",
      "GANs",
      "Diffusion",
      "Text generation",
      "Image generation",
      "Multimodal generation",
    ],
    projects: ["Tiny Text Generator", "Simple Image Generation Pipeline"],
    outcomes: [
      "Explain the difference between VAEs, GANs, and diffusion",
      "Train a simple generator on MNIST",
      "Pick the right generative approach for a task",
    ],
  },
  {
    slug: "llm-from-scratch",
    number: "10",
    title: "LLM From Scratch",
    tagline: "Build a Tiny GPT — tokenizer to trained model.",
    level: "AI Engineering",
    hours: 30,
    emoji: "🧬",
    overview:
      "The flagship module. You will implement a working GPT: BPE tokenizer, embeddings, positional encoding, attention, transformer blocks, training loop, and text generation.",
    topics: [
      "Tokenizer & vocabulary",
      "Token IDs",
      "Embeddings",
      "Positional encoding",
      "Attention",
      "Transformer block",
      "Language modeling",
      "Training loop",
      "Inference & sampling",
    ],
    projects: ["Tiny GPT — a working language model you built line-by-line"],
    outcomes: [
      "Deeply understand every part of a modern LLM",
      "Train a tiny model on a real corpus",
      "Explain temperature, top-k, and top-p sampling from code",
    ],
  },
  {
    slug: "llm-engineering",
    number: "11",
    title: "LLM Engineering",
    tagline: "Prompts, context, structured output, and function calling.",
    level: "AI Engineering",
    hours: 14,
    emoji: "🛠️",
    overview:
      "How professionals actually work with LLMs in production — reliable prompts, disciplined context management, structured JSON output, and tool use.",
    topics: [
      "Zero-shot & few-shot",
      "Role prompting",
      "Structured prompts",
      "Output constraints",
      "Context windows & compression",
      "Long-context strategies",
      "Structured output (JSON schema)",
      "Function calling & tools",
    ],
    projects: ["LLM function-calling agent that hits real APIs"],
    outcomes: [
      "Write prompts that don't break in production",
      "Get reliable JSON out of an LLM",
      "Wire an LLM into tool APIs",
    ],
  },
  {
    slug: "embeddings-vector-db",
    number: "12",
    title: "Embeddings & Vector Databases",
    tagline: "The foundation of semantic search and RAG.",
    level: "AI Engineering",
    hours: 12,
    emoji: "🧭",
    overview:
      "Turn text into vectors, measure semantic similarity, and store millions of embeddings in FAISS, Chroma, Qdrant, Weaviate, Pinecone, or pgvector.",
    topics: [
      "Embeddings",
      "Semantic similarity",
      "Cosine similarity",
      "Vector search",
      "Approximate nearest neighbor",
      "HNSW",
      "Chunking strategies",
      "Metadata & filtering",
      "Hybrid search",
      "Reranking",
    ],
    projects: ["Semantic search engine over your own documents"],
    outcomes: [
      "Pick the right vector DB for the workload",
      "Design chunking that doesn't destroy meaning",
      "Combine keyword + semantic + rerank",
    ],
  },
  {
    slug: "rag",
    number: "13",
    title: "Retrieval-Augmented Generation",
    tagline: "Give any LLM up-to-date, private, or long-tail knowledge.",
    level: "AI Engineering",
    hours: 22,
    emoji: "📚",
    overview:
      "From naive RAG to advanced retrieval: parent-child, HyDE, multi-query, reranking, Graph RAG, Agentic RAG, Corrective RAG, Self-RAG.",
    topics: [
      "Document loading",
      "Chunking",
      "Embedding",
      "Vector DB",
      "Retriever",
      "Parent-child retrieval",
      "Hybrid retrieval",
      "Metadata filtering",
      "Query rewriting",
      "Multi-query retrieval",
      "HyDE",
      "Reranking",
      "Context compression",
      "Graph RAG",
      "Agentic RAG",
      "Corrective RAG",
      "Self-RAG",
    ],
    projects: [
      "Chat with PDF",
      "Chat with Company Policies",
      "Chat with Source Code",
      "Customer Support Assistant",
      "Legal Document Assistant",
    ],
    outcomes: [
      "Ship a production-grade RAG pipeline",
      "Debug retrieval failures systematically",
      "Choose between naive, hybrid, and agentic RAG",
    ],
  },
  {
    slug: "fine-tuning",
    number: "14",
    title: "Fine-Tuning",
    tagline: "Adapt a base LLM to your data with LoRA and QLoRA.",
    level: "AI Engineering",
    hours: 16,
    emoji: "🎯",
    overview:
      "Pretraining vs fine-tuning vs instruction-tuning. SFT, LoRA, QLoRA, PEFT. When to fine-tune and — importantly — when not to.",
    topics: [
      "Pretraining",
      "Transfer learning",
      "Fine-tuning",
      "Instruction tuning",
      "SFT",
      "LoRA",
      "QLoRA",
      "PEFT",
      "Dataset preparation",
      "Evaluation",
      "Catastrophic forgetting",
    ],
    projects: ["Fine-tune a base model for customer support"],
    outcomes: [
      "Decide fine-tune vs RAG vs prompt-only",
      "Run a LoRA training job on consumer hardware",
      "Evaluate a fine-tuned model rigorously",
    ],
  },
  {
    slug: "llm-evaluation",
    number: "15",
    title: "LLM Evaluation",
    tagline: "You cannot ship what you cannot measure.",
    level: "AI Engineering",
    hours: 10,
    emoji: "📊",
    overview:
      "Traditional metrics fail on LLMs. Learn faithfulness, groundedness, hallucination detection, toxicity, bias, and LLM-as-judge patterns.",
    topics: [
      "Accuracy, precision, recall, F1",
      "Faithfulness",
      "Relevance",
      "Groundedness",
      "Context precision & recall",
      "Hallucination detection",
      "Toxicity & bias",
      "LLM as judge",
    ],
    projects: ["Build an LLM evaluation system for your own app"],
    outcomes: [
      "Set up a real eval pipeline",
      "Compare two prompts scientifically",
      "Detect hallucinations before your users do",
    ],
  },
  {
    slug: "ai-agents",
    number: "16",
    title: "AI Agents",
    tagline: "LLMs that think, plan, use tools, and act.",
    level: "Advanced",
    hours: 20,
    emoji: "🤖",
    overview:
      "The agent loop. Tool calling, ReAct, planning, memory, reflection, self-correction, task decomposition, routing, human-in-the-loop.",
    topics: [
      "Tool calling",
      "Agent loop",
      "ReAct",
      "Planning",
      "Memory",
      "Reflection",
      "Self-correction",
      "Task decomposition",
      "Routing",
      "Human-in-the-loop",
    ],
    projects: ["Research Agent", "SQL Agent", "Customer Support Agent", "Report Generation Agent"],
    outcomes: [
      "Design agents that don't loop forever",
      "Add safe tool use with guardrails",
      "Add memory and reflection to any agent",
    ],
  },
  {
    slug: "langchain-langgraph",
    number: "17",
    title: "LangChain & LangGraph",
    tagline: "The frameworks most AI teams standardize on.",
    level: "Advanced",
    hours: 14,
    emoji: "🕸️",
    overview:
      "LangChain for chains and retrievers; LangGraph for stateful, cyclic agent workflows with retries and human approval nodes.",
    topics: [
      "Prompt templates",
      "Models & tools",
      "Retrievers",
      "Chains",
      "Structured output",
      "LangGraph nodes & edges",
      "State management",
      "Retry logic",
      "Human approval nodes",
    ],
    projects: ["Research Agent", "SQL Agent", "Customer Support Agent", "Report Generation Agent"],
    outcomes: [
      "Build an agent as a state machine, not spaghetti",
      "Add retries and self-correction cleanly",
      "Debug agent graphs visually",
    ],
  },
  {
    slug: "mcp",
    number: "18",
    title: "Model Context Protocol",
    tagline: "The USB-C for AI tools.",
    level: "Advanced",
    hours: 10,
    emoji: "🔌",
    overview:
      "MCP lets any AI assistant talk to any tool through a single protocol. Build clients, servers, tools, resources, and prompts.",
    topics: [
      "What is MCP?",
      "MCP Client & Server",
      "Resources",
      "Tools",
      "Prompts",
      "Transport",
      "Security",
      "Authentication",
    ],
    projects: ["Weather MCP", "Database MCP", "File System MCP", "GitHub MCP", "Internal Company MCP"],
    outcomes: [
      "Expose your internal tools to any AI assistant",
      "Design secure MCP servers",
      "Consume MCP servers from Claude or your own agents",
    ],
  },
  {
    slug: "multi-agent",
    number: "19",
    title: "Multi-Agent Systems",
    tagline: "Teams of AI agents that coordinate to solve real work.",
    level: "Advanced",
    hours: 18,
    emoji: "🧑‍🤝‍🧑",
    overview:
      "Supervisors, workers, delegation, consensus, debate, parallel agents, hierarchical agents. Build an AI software development team.",
    topics: [
      "Supervisor & worker agents",
      "Delegation",
      "Communication",
      "Shared memory",
      "Agent routing",
      "Consensus & debate",
      "Parallel agents",
      "Sequential agents",
      "Hierarchical agents",
    ],
    projects: ["AI Software Development Team (PM → Architect → Dev → Tester → Reviewer)"],
    outcomes: [
      "Design agent teams that don't step on each other",
      "Add debate and consensus for reliability",
      "Scale from one agent to a coordinated fleet",
    ],
  },
  {
    slug: "multimodal",
    number: "20",
    title: "Multimodal AI",
    tagline: "Vision, audio, and video, joined to language.",
    level: "Advanced",
    hours: 14,
    emoji: "🎥",
    overview:
      "Vision-language models, speech-to-text, text-to-speech, document AI, and image understanding, all wired into LLM pipelines.",
    topics: [
      "Vision + LLM",
      "Audio + LLM",
      "Video + LLM",
      "Image understanding",
      "Document understanding",
      "OCR",
      "Speech-to-text",
      "Text-to-speech",
    ],
    projects: ["AI Invoice Processor", "Meeting Assistant with summaries and action items"],
    outcomes: [
      "Wire vision models into agent workflows",
      "Build production document AI",
      "Ship a meeting assistant end-to-end",
    ],
  },
  {
    slug: "ai-and-databases",
    number: "21",
    title: "AI + Databases",
    tagline: "Text-to-SQL, schema understanding, and safe query execution.",
    level: "Advanced",
    hours: 12,
    emoji: "🗄️",
    overview:
      "Let users ask natural-language questions of your database — safely. Schema retrieval, query generation, validation, execution, and result explanation.",
    topics: [
      "SQL fundamentals",
      "Text-to-SQL",
      "Database agents",
      "Schema understanding",
      "Query generation",
      "Query validation",
      "Query execution",
      "Result interpretation",
      "Row-level permissions",
      "Security",
    ],
    projects: ["Ask questions about a company database in plain English"],
    outcomes: [
      "Ship text-to-SQL without SQL injection",
      "Handle multi-table schemas well",
      "Return answers plus charts, not just rows",
    ],
  },
  {
    slug: "ai-infrastructure",
    number: "22",
    title: "AI Infrastructure",
    tagline: "Serving, scaling, and running models in production.",
    level: "Advanced",
    hours: 14,
    emoji: "🏗️",
    overview:
      "FastAPI, vLLM, TGI, Ollama, Docker, Kubernetes, GPU, quantization, batching, KV cache. What actually powers a production LLM.",
    topics: [
      "FastAPI, vLLM, TGI, Ollama",
      "Model serving & streaming",
      "Docker & Kubernetes",
      "GPU & CUDA",
      "AWS / Azure / GCP",
      "Batching",
      "Caching & KV cache",
      "Quantization",
      "Model & data parallelism",
    ],
    projects: ["Deploy an LLM API with autoscaling, batching, and streaming"],
    outcomes: [
      "Serve an LLM at real QPS",
      "Cut serving cost with quantization + batching",
      "Understand what breaks at scale, and why",
    ],
  },
  {
    slug: "ai-security",
    number: "23",
    title: "AI Security & Responsible AI",
    tagline: "Attack the AI. Defend the AI.",
    level: "Advanced",
    hours: 12,
    emoji: "🛡️",
    overview:
      "Prompt injection, jailbreaking, data leakage, tool abuse, excessive agency, RAG poisoning. Then the defensive playbook — guardrails, RBAC, audit logs.",
    topics: [
      "Prompt injection",
      "Jailbreaking",
      "Data leakage",
      "PII",
      "Model abuse",
      "Tool abuse",
      "Excessive agency",
      "RAG poisoning",
      "Supply-chain attacks",
      "Authentication & authorization",
      "Audit logging",
      "Guardrails",
    ],
    projects: ["Interactive security lab — attack a live agent, then harden it"],
    outcomes: [
      "Threat-model an AI feature",
      "Add layered guardrails that actually work",
      "Pass a security review",
    ],
  },
  {
    slug: "ai-production",
    number: "24",
    title: "AI Production Engineering",
    tagline: "Observability, cost, reliability, and rollouts for AI systems.",
    level: "Advanced",
    hours: 14,
    emoji: "🚀",
    overview:
      "Async processing, queues, caching, logs, metrics, tracing, cost & token monitoring, rate limiting, retries, circuit breakers, model fallback, versioning, CI/CD.",
    topics: [
      "Architecture",
      "API design",
      "Async processing & queues",
      "Caching",
      "Observability",
      "Logging & metrics",
      "Tracing",
      "Cost & token monitoring",
      "Rate limiting & retries",
      "Circuit breakers",
      "Model fallback",
      "Versioning",
      "CI/CD",
      "Testing",
    ],
    projects: ["Production-grade AI API with dashboards, retries, and fallback"],
    outcomes: [
      "Wake up to alerts, not surprises",
      "Cut token spend with caching and fallback",
      "Roll out prompt/model changes safely",
    ],
  },
  {
    slug: "ai-system-design",
    number: "25",
    title: "AI System Design",
    tagline: "Design ChatGPT-scale systems on a whiteboard.",
    level: "Advanced",
    hours: 12,
    emoji: "🗺️",
    overview:
      "Case studies: ChatGPT, RAG platform, AI coding assistant, AI search, recommendation, multi-agent platform, enterprise AI. A repeatable design flow.",
    topics: [
      "Requirements & constraints",
      "Architecture",
      "Components & data flow",
      "API design",
      "Database choices",
      "LLM placement",
      "Scaling",
      "Security",
      "Cost",
      "Failure scenarios",
    ],
    projects: [
      "Design ChatGPT-like system",
      "Design RAG platform",
      "Design AI customer support",
      "Design AI coding assistant",
      "Design enterprise AI platform",
    ],
    outcomes: [
      "Pass an AI system design interview",
      "Whiteboard an AI product end-to-end",
      "Justify architectural trade-offs with numbers",
    ],
  },
  {
    slug: "capstone",
    number: "26",
    title: "Capstone Projects",
    tagline: "Portfolio-ready projects for every level.",
    level: "Advanced",
    hours: 40,
    emoji: "🏆",
    overview:
      "One capstone per skill level, each shipped as a public repo with a live demo. From an AI chatbot to a full enterprise agentic platform.",
    topics: [
      "Requirements & scoping",
      "Architecture design",
      "Iterative delivery",
      "Evaluation & testing",
      "Deployment",
      "Documentation",
      "Demo & write-up",
    ],
    projects: [
      "Beginner — AI Chatbot",
      "Intermediate — PDF RAG Assistant",
      "Advanced — Enterprise Knowledge Assistant",
      "Expert — Multi-Agent Research System",
      "Senior — AI Software Development Platform",
      "Architect — Enterprise Agentic AI Platform",
    ],
    outcomes: [
      "Ship a GitHub-ready portfolio",
      "Explain each project like a senior engineer",
      "Have real work to show, not a certificate",
    ],
  },
];

export const levels: Level[] = ["Foundations", "AI Core", "AI Engineering", "Advanced"];

export function tracksByLevel(level: Level) {
  return tracks.filter((t) => t.level === level);
}

export function getTrack(slug: string) {
  return tracks.find((t) => t.slug === slug);
}

export function totalHours() {
  return tracks.reduce((sum, t) => sum + t.hours, 0);
}
