export type Level = "Foundations" | "AI Core" | "AI Engineering" | "Advanced";

export interface Track {
  slug: string;
  number: string;
  title: string;
  tagline: string;
  level: Level;
  hours: number;
  emoji: string;
  overview: string;
  topics: string[];
  projects: string[];
  outcomes: string[];
}

export const tracks: Track[] = [
  {
    slug: "developer-setup",
    number: "00",
    title: "Developer Setup",
    tagline: "Build a local AI development environment from scratch.",
    level: "Foundations",
    hours: 6,
    emoji: "🧰",
    overview:
      "Every AI engineer needs a rock-solid local setup. In this track you install Python, learn virtual environments and package managers, get comfortable with Git, Docker, and the command line, and stand up your first local LLM through Ollama.",
    topics: [
      "Python",
      "Python virtual environments",
      "pip",
      "uv",
      "Jupyter",
      "VS Code",
      "Git",
      "GitHub",
      "Linux basics",
      "CLI",
      "Docker",
      "REST APIs",
      "JSON",
      "HTTP",
      "Environment variables",
      "API keys",
      "GPU basics",
      "CUDA basics",
      "Local AI setup",
      "Ollama",
    ],
    projects: ["Local AI Development Environment (React + FastAPI + Ollama)"],
    outcomes: [
      "Run a local LLM on your own machine",
      "Ship a React frontend that talks to a FastAPI backend",
      "Manage Python dependencies with uv confidently",
    ],
  },
  {
    slug: "math-for-ai",
    number: "01",
    title: "Mathematics for AI",
    tagline: "Just enough linear algebra, calculus, probability, and stats.",
    level: "Foundations",
    hours: 20,
    emoji: "📐",
    overview:
      "The math you actually need for AI — nothing more, nothing less. Vectors, gradients, probability, and statistics taught through code and visualization, not proofs.",
    topics: [
      "Scalars, vectors, matrices, tensors",
      "Dot product",
      "Matrix multiplication",
      "Norms & distance",
      "Eigenvalues & eigenvectors",
      "PCA",
      "Embeddings",
      "Derivatives",
      "Partial derivatives",
      "Chain rule",
      "Gradient descent",
      "Probability & Bayes",
      "Distributions",
      "Expectation & variance",
      "Maximum likelihood",
      "Sampling & hypothesis testing",
    ],
    projects: ["House Price Predictor built purely from gradients"],
    outcomes: [
      "Read AI papers without getting lost in notation",
      "Derive gradient updates by hand",
      "Understand why embeddings work geometrically",
    ],
  },
  {
    slug: "classical-ml",
    number: "02",
    title: "Classical Machine Learning",
    tagline: "The algorithms that still power 80% of ML in production.",
    level: "AI Core",
    hours: 24,
    emoji: "🌲",
    overview:
      "Regression, trees, gradient boosting, clustering, and evaluation. You will train, evaluate, and debug real models on real data.",
    topics: [
      "Linear & polynomial regression",
      "Logistic regression",
      "Decision trees",
      "Random forest",
      "Gradient boosting",
      "XGBoost / LightGBM",
      "K-Means",
      "Hierarchical clustering",
      "DBSCAN",
      "PCA & dimensionality reduction",
      "Overfitting, underfitting, bias/variance",
      "Cross-validation",
      "Feature engineering & selection",
      "Accuracy, precision, recall, F1, ROC-AUC",
      "MAE, MSE, RMSE, R²",
    ],
    projects: [
      "Customer Churn Predictor",
      "Loan Approval Predictor",
      "House Price Predictor",
      "Fraud Detection",
      "Customer Segmentation",
    ],
    outcomes: [
      "Pick the right algorithm for a tabular problem",
      "Diagnose overfitting from a learning curve",
      "Explain a model to a business stakeholder",
    ],
  },
  {
    slug: "ml-from-scratch",
    number: "03",
    title: "ML From Scratch",
    tagline: "Build the algorithms before you use the library.",
    level: "AI Core",
    hours: 18,
    emoji: "🧪",
    overview:
      "Implement linear regression, logistic regression, k-means, decision trees, and gradient descent using only Python and NumPy — then compare against scikit-learn line-for-line.",
    topics: [
      "Linear regression from scratch",
      "Logistic regression from scratch",
      "K-means from scratch",
      "Decision tree fundamentals",
      "Gradient descent",
      "Loss functions",
      "Optimization",
      "Evaluation from scratch",
    ],
    projects: ["Numpy-only ML library that mirrors scikit-learn's API"],
    outcomes: [
      "Never treat an ML algorithm as a black box again",
      "Reason about numerical stability",
      "Debug convergence issues from first principles",
    ],
  },
  {
    slug: "deep-learning",
    number: "04",
    title: "Deep Learning",
    tagline: "Neural networks, backprop, and the optimizers that make them learn.",
    level: "AI Core",
    hours: 28,
    emoji: "🧠",
    overview:
      "From a single neuron to deep networks. You will implement backpropagation by hand, then use it to train a network on real data.",
    topics: [
      "Neuron & perceptron",
      "Weights & bias",
      "Sigmoid, tanh, ReLU, GELU, softmax",
      "Forward propagation",
      "Backpropagation",
      "MSE, BCE, CCE loss",
      "SGD, momentum, AdaGrad, RMSProp, Adam, AdamW",
      "Dropout & weight decay",
      "Batch & layer normalization",
      "Early stopping",
    ],
    projects: ["Handwritten neural network trained on MNIST — no framework"],
    outcomes: [
      "Derive backpropagation from calculus",
      "Choose an optimizer with intent, not superstition",
      "Debug vanishing/exploding gradients",
    ],
  },
  {
    slug: "pytorch",
    number: "05",
    title: "PyTorch",
    tagline: "The framework used by every serious AI lab and startup.",
    level: "AI Core",
    hours: 16,
    emoji: "🔥",
    overview:
      "Tensors, autograd, datasets, dataloaders, training loops. You'll build a full training pipeline and train on GPU.",
    topics: [
      "Installation",
      "Tensors & operations",
      "Autograd",
      "Datasets & DataLoaders",
      "Models & modules",
      "Training loops",
      "Evaluation",
      "GPU training",
      "Saving & loading models",
      "Transfer learning",
    ],
    projects: ["MNIST classifier with an interactive hyperparameter panel"],
    outcomes: [
      "Write idiomatic PyTorch code",
      "Move workloads to GPU without breaking anything",
      "Save, load, and share trained models",
    ],
  },
  {
    slug: "computer-vision",
    number: "06",
    title: "Computer Vision",
    tagline: "Teach machines to see — from pixels to Vision Transformers.",
    level: "AI Core",
    hours: 20,
    emoji: "👁️",
    overview:
      "How images become tensors, how convolutions extract features, and how modern vision models detect, segment, and understand images.",
    topics: [
      "Image representation & RGB",
      "Convolution, kernels, stride, padding",
      "Pooling",
      "CNNs",
      "Transfer learning",
      "Object detection",
      "Image segmentation",
      "OCR",
      "Vision Transformers",
    ],
    projects: [
      "Face Detection",
      "Document Scanner",
      "Invoice OCR",
      "Plant Disease Detection",
      "Vehicle Detection",
      "Object Counter",
    ],
    outcomes: [
      "Fine-tune a pretrained CNN in an afternoon",
      "Build an OCR pipeline that reads real invoices",
      "Deploy a vision model behind an API",
    ],
  },
  {
    slug: "nlp",
    number: "07",
    title: "Natural Language Processing",
    tagline: "From bag-of-words to attention — the road that led to LLMs.",
    level: "AI Core",
    hours: 18,
    emoji: "💬",
    overview:
      "Understand the entire NLP evolution: tokenization, TF-IDF, word embeddings, RNNs, LSTMs, and finally attention. Every step in context.",
    topics: [
      "Text preprocessing",
      "Tokenization",
      "Stemming & lemmatization",
      "N-grams & TF-IDF",
      "Word embeddings (Word2Vec, GloVe)",
      "Semantic similarity",
      "RNN, LSTM, GRU",
      "Attention",
    ],
    projects: ["Text classifier", "Semantic similarity engine", "Simple translator"],
    outcomes: [
      "Explain why attention replaced recurrence",
      "Build a working sentence-similarity model",
      "Preprocess messy text like a pro",
    ],
  },
  {
    slug: "transformers",
    number: "08",
    title: "Transformers",
    tagline: "The single architecture behind every modern AI system.",
    level: "AI Engineering",
    hours: 20,
    emoji: "⚡",
    overview:
      "Query, key, value. Self-attention, multi-head attention, positional encoding, encoders, decoders. Interactive visualizations for every step.",
    topics: [
      "Attention",
      "Query, Key, Value",
      "Scaled dot-product attention",
      "Self-attention",
      "Multi-head attention",
      "Positional encoding",
      "Feed-forward networks",
      "Residual connections",
      "Layer normalization",
      "Encoder & decoder",
      "Causal masking",
    ],
    projects: ["Attention visualizer", "Toy encoder-decoder built in PyTorch"],
    outcomes: [
      "Draw the Transformer architecture from memory",
      "Explain why attention scales better than RNNs",
      "Read the original 'Attention is All You Need' paper with clarity",
    ],
  },
  {
    slug: "generative-ai",
    number: "09",
    title: "Generative AI",
    tagline: "Autoencoders, VAEs, GANs, and diffusion.",
    level: "AI Engineering",
    hours: 16,
    emoji: "🎨",
    overview:
      "How machines generate — text, images, audio. Autoencoders and VAEs for reconstruction, GANs for adversarial generation, diffusion for state-of-the-art image models.",
    topics: [
      "Generative models",
      "Autoencoders",
      "Variational Autoencoders",
      "GANs",
      "Diffusion",
      "Text generation",
      "Image generation",
      "Multimodal generation",
    ],
    projects: ["Tiny Text Generator", "Simple Image Generation Pipeline"],
    outcomes: [
      "Explain the difference between VAEs, GANs, and diffusion",
      "Train a simple generator on MNIST",
      "Pick the right generative approach for a task",
    ],
  },
  {
    slug: "llm-from-scratch",
    number: "10",
    title: "LLM From Scratch",
    tagline: "Build a Tiny GPT — tokenizer to trained model.",
    level: "AI Engineering",
    hours: 30,
    emoji: "🧬",
    overview:
      "The flagship module. You will implement a working GPT: BPE tokenizer, embeddings, positional encoding, attention, transformer blocks, training loop, and text generation.",
    topics: [
      "Tokenizer & vocabulary",
      "Token IDs",
      "Embeddings",
      "Positional encoding",
      "Attention",
      "Transformer block",
      "Language modeling",
      "Training loop",
      "Inference & sampling",
    ],
    projects: ["Tiny GPT — a working language model you built line-by-line"],
    outcomes: [
      "Deeply understand every part of a modern LLM",
      "Train a tiny model on a real corpus",
      "Explain temperature, top-k, and top-p sampling from code",
    ],
  },
  {
    slug: "llm-engineering",
    number: "11",
    title: "LLM Engineering",
    tagline: "Prompts, context, structured output, and function calling.",
    level: "AI Engineering",
    hours: 14,
    emoji: "🛠️",
    overview:
      "How professionals actually work with LLMs in production — reliable prompts, disciplined context management, structured JSON output, and tool use.",
    topics: [
      "Zero-shot & few-shot",
      "Role prompting",
      "Structured prompts",
      "Output constraints",
      "Context windows & compression",
      "Long-context strategies",
      "Structured output (JSON schema)",
      "Function calling & tools",
    ],
    projects: ["LLM function-calling agent that hits real APIs"],
    outcomes: [
      "Write prompts that don't break in production",
      "Get reliable JSON out of an LLM",
      "Wire an LLM into tool APIs",
    ],
  },
  {
    slug: "embeddings-vector-db",
    number: "12",
    title: "Embeddings & Vector Databases",
    tagline: "The foundation of semantic search and RAG.",
    level: "AI Engineering",
    hours: 12,
    emoji: "🧭",
    overview:
      "Turn text into vectors, measure semantic similarity, and store millions of embeddings in FAISS, Chroma, Qdrant, Weaviate, Pinecone, or pgvector.",
    topics: [
      "Embeddings",
      "Semantic similarity",
      "Cosine similarity",
      "Vector search",
      "Approximate nearest neighbor",
      "HNSW",
      "Chunking strategies",
      "Metadata & filtering",
      "Hybrid search",
      "Reranking",
    ],
    projects: ["Semantic search engine over your own documents"],
    outcomes: [
      "Pick the right vector DB for the workload",
      "Design chunking that doesn't destroy meaning",
      "Combine keyword + semantic + rerank",
    ],
  },
  {
    slug: "rag",
    number: "13",
    title: "Retrieval-Augmented Generation",
    tagline: "Give any LLM up-to-date, private, or long-tail knowledge.",
    level: "AI Engineering",
    hours: 22,
    emoji: "📚",
    overview:
      "From naive RAG to advanced retrieval: parent-child, HyDE, multi-query, reranking, Graph RAG, Agentic RAG, Corrective RAG, Self-RAG.",
    topics: [
      "Document loading",
      "Chunking",
      "Embedding",
      "Vector DB",
      "Retriever",
      "Parent-child retrieval",
      "Hybrid retrieval",
      "Metadata filtering",
      "Query rewriting",
      "Multi-query retrieval",
      "HyDE",
      "Reranking",
      "Context compression",
      "Graph RAG",
      "Agentic RAG",
      "Corrective RAG",
      "Self-RAG",
    ],
    projects: [
      "Chat with PDF",
      "Chat with Company Policies",
      "Chat with Source Code",
      "Customer Support Assistant",
      "Legal Document Assistant",
    ],
    outcomes: [
      "Ship a production-grade RAG pipeline",
      "Debug retrieval failures systematically",
      "Choose between naive, hybrid, and agentic RAG",
    ],
  },
  {
    slug: "fine-tuning",
    number: "14",
    title: "Fine-Tuning",
    tagline: "Adapt a base LLM to your data with LoRA and QLoRA.",
    level: "AI Engineering",
    hours: 16,
    emoji: "🎯",
    overview:
      "Pretraining vs fine-tuning vs instruction-tuning. SFT, LoRA, QLoRA, PEFT. When to fine-tune and — importantly — when not to.",
    topics: [
      "Pretraining",
      "Transfer learning",
      "Fine-tuning",
      "Instruction tuning",
      "SFT",
      "LoRA",
      "QLoRA",
      "PEFT",
      "Dataset preparation",
      "Evaluation",
      "Catastrophic forgetting",
    ],
    projects: ["Fine-tune a base model for customer support"],
    outcomes: [
      "Decide fine-tune vs RAG vs prompt-only",
      "Run a LoRA training job on consumer hardware",
      "Evaluate a fine-tuned model rigorously",
    ],
  },
  {
    slug: "llm-evaluation",
    number: "15",
    title: "LLM Evaluation",
    tagline: "You cannot ship what you cannot measure.",
    level: "AI Engineering",
    hours: 10,
    emoji: "📊",
    overview:
      "Traditional metrics fail on LLMs. Learn faithfulness, groundedness, hallucination detection, toxicity, bias, and LLM-as-judge patterns.",
    topics: [
      "Accuracy, precision, recall, F1",
      "Faithfulness",
      "Relevance",
      "Groundedness",
      "Context precision & recall",
      "Hallucination detection",
      "Toxicity & bias",
      "LLM as judge",
    ],
    projects: ["Build an LLM evaluation system for your own app"],
    outcomes: [
      "Set up a real eval pipeline",
      "Compare two prompts scientifically",
      "Detect hallucinations before your users do",
    ],
  },
  {
    slug: "ai-agents",
    number: "16",
    title: "AI Agents",
    tagline: "LLMs that think, plan, use tools, and act.",
    level: "Advanced",
    hours: 20,
    emoji: "🤖",
    overview:
      "The agent loop. Tool calling, ReAct, planning, memory, reflection, self-correction, task decomposition, routing, human-in-the-loop.",
    topics: [
      "Tool calling",
      "Agent loop",
      "ReAct",
      "Planning",
      "Memory",
      "Reflection",
      "Self-correction",
      "Task decomposition",
      "Routing",
      "Human-in-the-loop",
    ],
    projects: ["Research Agent", "SQL Agent", "Customer Support Agent", "Report Generation Agent"],
    outcomes: [
      "Design agents that don't loop forever",
      "Add safe tool use with guardrails",
      "Add memory and reflection to any agent",
    ],
  },
  {
    slug: "langchain-langgraph",
    number: "17",
    title: "LangChain & LangGraph",
    tagline: "The frameworks most AI teams standardize on.",
    level: "Advanced",
    hours: 14,
    emoji: "🕸️",
    overview:
      "LangChain for chains and retrievers; LangGraph for stateful, cyclic agent workflows with retries and human approval nodes.",
    topics: [
      "Prompt templates",
      "Models & tools",
      "Retrievers",
      "Chains",
      "Structured output",
      "LangGraph nodes & edges",
      "State management",
      "Retry logic",
      "Human approval nodes",
    ],
    projects: ["Research Agent", "SQL Agent", "Customer Support Agent", "Report Generation Agent"],
    outcomes: [
      "Build an agent as a state machine, not spaghetti",
      "Add retries and self-correction cleanly",
      "Debug agent graphs visually",
    ],
  },
  {
    slug: "mcp",
    number: "18",
    title: "Model Context Protocol",
    tagline: "The USB-C for AI tools.",
    level: "Advanced",
    hours: 10,
    emoji: "🔌",
    overview:
      "MCP lets any AI assistant talk to any tool through a single protocol. Build clients, servers, tools, resources, and prompts.",
    topics: [
      "What is MCP?",
      "MCP Client & Server",
      "Resources",
      "Tools",
      "Prompts",
      "Transport",
      "Security",
      "Authentication",
    ],
    projects: ["Weather MCP", "Database MCP", "File System MCP", "GitHub MCP", "Internal Company MCP"],
    outcomes: [
      "Expose your internal tools to any AI assistant",
      "Design secure MCP servers",
      "Consume MCP servers from Claude or your own agents",
    ],
  },
  {
    slug: "multi-agent",
    number: "19",
    title: "Multi-Agent Systems",
    tagline: "Teams of AI agents that coordinate to solve real work.",
    level: "Advanced",
    hours: 18,
    emoji: "🧑‍🤝‍🧑",
    overview:
      "Supervisors, workers, delegation, consensus, debate, parallel agents, hierarchical agents. Build an AI software development team.",
    topics: [
      "Supervisor & worker agents",
      "Delegation",
      "Communication",
      "Shared memory",
      "Agent routing",
      "Consensus & debate",
      "Parallel agents",
      "Sequential agents",
      "Hierarchical agents",
    ],
    projects: ["AI Software Development Team (PM → Architect → Dev → Tester → Reviewer)"],
    outcomes: [
      "Design agent teams that don't step on each other",
      "Add debate and consensus for reliability",
      "Scale from one agent to a coordinated fleet",
    ],
  },
  {
    slug: "multimodal",
    number: "20",
    title: "Multimodal AI",
    tagline: "Vision, audio, and video, joined to language.",
    level: "Advanced",
    hours: 14,
    emoji: "🎥",
    overview:
      "Vision-language models, speech-to-text, text-to-speech, document AI, and image understanding, all wired into LLM pipelines.",
    topics: [
      "Vision + LLM",
      "Audio + LLM",
      "Video + LLM",
      "Image understanding",
      "Document understanding",
      "OCR",
      "Speech-to-text",
      "Text-to-speech",
    ],
    projects: ["AI Invoice Processor", "Meeting Assistant with summaries and action items"],
    outcomes: [
      "Wire vision models into agent workflows",
      "Build production document AI",
      "Ship a meeting assistant end-to-end",
    ],
  },
  {
    slug: "ai-and-databases",
    number: "21",
    title: "AI + Databases",
    tagline: "Text-to-SQL, schema understanding, and safe query execution.",
    level: "Advanced",
    hours: 12,
    emoji: "🗄️",
    overview:
      "Let users ask natural-language questions of your database — safely. Schema retrieval, query generation, validation, execution, and result explanation.",
    topics: [
      "SQL fundamentals",
      "Text-to-SQL",
      "Database agents",
      "Schema understanding",
      "Query generation",
      "Query validation",
      "Query execution",
      "Result interpretation",
      "Row-level permissions",
      "Security",
    ],
    projects: ["Ask questions about a company database in plain English"],
    outcomes: [
      "Ship text-to-SQL without SQL injection",
      "Handle multi-table schemas well",
      "Return answers plus charts, not just rows",
    ],
  },
  {
    slug: "ai-infrastructure",
    number: "22",
    title: "AI Infrastructure",
    tagline: "Serving, scaling, and running models in production.",
    level: "Advanced",
    hours: 14,
    emoji: "🏗️",
    overview:
      "FastAPI, vLLM, TGI, Ollama, Docker, Kubernetes, GPU, quantization, batching, KV cache. What actually powers a production LLM.",
    topics: [
      "FastAPI, vLLM, TGI, Ollama",
      "Model serving & streaming",
      "Docker & Kubernetes",
      "GPU & CUDA",
      "AWS / Azure / GCP",
      "Batching",
      "Caching & KV cache",
      "Quantization",
      "Model & data parallelism",
    ],
    projects: ["Deploy an LLM API with autoscaling, batching, and streaming"],
    outcomes: [
      "Serve an LLM at real QPS",
      "Cut serving cost with quantization + batching",
      "Understand what breaks at scale, and why",
    ],
  },
  {
    slug: "ai-security",
    number: "23",
    title: "AI Security & Responsible AI",
    tagline: "Attack the AI. Defend the AI.",
    level: "Advanced",
    hours: 12,
    emoji: "🛡️",
    overview:
      "Prompt injection, jailbreaking, data leakage, tool abuse, excessive agency, RAG poisoning. Then the defensive playbook — guardrails, RBAC, audit logs.",
    topics: [
      "Prompt injection",
      "Jailbreaking",
      "Data leakage",
      "PII",
      "Model abuse",
      "Tool abuse",
      "Excessive agency",
      "RAG poisoning",
      "Supply-chain attacks",
      "Authentication & authorization",
      "Audit logging",
      "Guardrails",
    ],
    projects: ["Interactive security lab — attack a live agent, then harden it"],
    outcomes: [
      "Threat-model an AI feature",
      "Add layered guardrails that actually work",
      "Pass a security review",
    ],
  },
  {
    slug: "ai-production",
    number: "24",
    title: "AI Production Engineering",
    tagline: "Observability, cost, reliability, and rollouts for AI systems.",
    level: "Advanced",
    hours: 14,
    emoji: "🚀",
    overview:
      "Async processing, queues, caching, logs, metrics, tracing, cost & token monitoring, rate limiting, retries, circuit breakers, model fallback, versioning, CI/CD.",
    topics: [
      "Architecture",
      "API design",
      "Async processing & queues",
      "Caching",
      "Observability",
      "Logging & metrics",
      "Tracing",
      "Cost & token monitoring",
      "Rate limiting & retries",
      "Circuit breakers",
      "Model fallback",
      "Versioning",
      "CI/CD",
      "Testing",
    ],
    projects: ["Production-grade AI API with dashboards, retries, and fallback"],
    outcomes: [
      "Wake up to alerts, not surprises",
      "Cut token spend with caching and fallback",
      "Roll out prompt/model changes safely",
    ],
  },
  {
    slug: "ai-system-design",
    number: "25",
    title: "AI System Design",
    tagline: "Design ChatGPT-scale systems on a whiteboard.",
    level: "Advanced",
    hours: 12,
    emoji: "🗺️",
    overview:
      "Case studies: ChatGPT, RAG platform, AI coding assistant, AI search, recommendation, multi-agent platform, enterprise AI. A repeatable design flow.",
    topics: [
      "Requirements & constraints",
      "Architecture",
      "Components & data flow",
      "API design",
      "Database choices",
      "LLM placement",
      "Scaling",
      "Security",
      "Cost",
      "Failure scenarios",
    ],
    projects: [
      "Design ChatGPT-like system",
      "Design RAG platform",
      "Design AI customer support",
      "Design AI coding assistant",
      "Design enterprise AI platform",
    ],
    outcomes: [
      "Pass an AI system design interview",
      "Whiteboard an AI product end-to-end",
      "Justify architectural trade-offs with numbers",
    ],
  },
  {
    slug: "capstone",
    number: "26",
    title: "Capstone Projects",
    tagline: "Portfolio-ready projects for every level.",
    level: "Advanced",
    hours: 40,
    emoji: "🏆",
    overview:
      "One capstone per skill level, each shipped as a public repo with a live demo. From an AI chatbot to a full enterprise agentic platform.",
    topics: [
      "Requirements & scoping",
      "Architecture design",
      "Iterative delivery",
      "Evaluation & testing",
      "Deployment",
      "Documentation",
      "Demo & write-up",
    ],
    projects: [
      "Beginner — AI Chatbot",
      "Intermediate — PDF RAG Assistant",
      "Advanced — Enterprise Knowledge Assistant",
      "Expert — Multi-Agent Research System",
      "Senior — AI Software Development Platform",
      "Architect — Enterprise Agentic AI Platform",
    ],
    outcomes: [
      "Ship a GitHub-ready portfolio",
      "Explain each project like a senior engineer",
      "Have real work to show, not a certificate",
    ],
  },
];

export const levels: Level[] = ["Foundations", "AI Core", "AI Engineering", "Advanced"];

export function tracksByLevel(level: Level) {
  return tracks.filter((t) => t.level === level);
}

export function getTrack(slug: string) {
  return tracks.find((t) => t.slug === slug);
}

export function totalHours() {
  return tracks.reduce((sum, t) => sum + t.hours, 0);
}
